- fix in checking is netforking is up.
Changed files:
    ypbind.init -> 1.6

diff --git a/ypbind.init b/ypbind.init
--- a/ypbind.init
+++ b/ypbind.init
@@ -23,7 +23,10 @@
 [ -f /etc/sysconfig/ypbind ] && . /etc/sysconfig/ypbind
 
 # Check that networking is up.
-[ "${NETWORKING}" = "no" ] && echo "Error: Networking is down" && exit 0
+if [ "${NETWORKING}" = "no" ]; then
+	echo "WARNING: Networking is down. Ypbind service can't be runed."
+	exit 1
+fi
 
 
 # See how we were called.
